services:
  api:
    build:
      context: ./backend
    container_name: fastnotes-api
    ports:
      - "2345:2345"

  ui:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://notesapi.fitzythe.dev # Pass as build arg
    container_name: fastnotes-ui
    ports:
      - "5432:5432"
    depends_on:
      - api
