services:
  api:
    build:
      context: ./backend
    container_name: fastnotes-api

  ui:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://notesapi.fitzythe.dev # Pass as build arg
    container_name: fastnotes-ui
    depends_on:
      - api
