services:
  api:
    build:
      context: ./backend
    container_name: fastnotes-api
    ports:
      - "8000:8000"

  # ui:
  #   build:
  #     context: ./frontend
  #     args:
  #       VITE_API_URL: /api
